### ISSUE TITLE
Convert existing django Model to MP_Node

### ISSUE THREAD

**Issue by shafiqr** [django-treebeard/django-treebeard#134] opened 2019-01-27 18:40 UTC
I have a Django model named User derived from models.Model. I tried converting it to MP_Node by inheriting it from MP_Node which created depth, path and numchild columns. I already have a lot of users in my production database. 

I want to organize them in an materialized path tree but when I want to use add_root api with instance set to a user object retrieved from database, it errors out saying that "Attempted to add a tree node that is already in database". That is exactly what what I want to do. I don't want to delete the user and add it back because it may trigger deletion of some rows in other tables due to foreign key constraints.

How can I just update the existing rows in user table as nodes of MP Tree using django-treebeard APIs?

**Comment by jrief** [comment] 2019-01-27 20:57
Create your new User model inheriting from `MP_Node`. Then migrate the users from one table into the other one. After that switch `AUTH_USER_MODEL` to the new model. This prevents all sorts of unwanted signal triggers.

**Comment by shafiqr** [comment] 2019-01-28 00:33
Unfortunately, my User model is not Django's default user model. Think of it as a custom node is tree. Is it fair to say that at this moment this library doesn't handle dealing with an existing model and its rows in a database. Like it can't add a row as a root/child if provided with the row's primary key that already exist in database by updating the path, depth and numchild columns for the row.

**Comment by jrief** [comment] 2019-01-28 07:51
> Is it fair to say that at this moment this library doesn't handle dealing with an existing model and its rows in a database.

Not at all. It can candle every kind of Django model if applied correctly.

Closing this because it is not a bug, or feature request.

**Closed by jrief** 2019-01-28 07:51 UTC
