### ISSUE TITLE
Multiple tree roots

### ISSUE THREAD

**Issue by jrief** [django-treebeard/django-treebeard#47] opened 2016-11-23 10:35 UTC
Currently **django-treebeard** does not offer any functionality to handle more than one root out of the box. If one wants to support more than one root, he must add another field to the implementation of his model version, inheriting from MP_Node.

This additional field is required in order to distinguish the different roots.  However, when adding a child to an existing node, the value of this field must be manually copied from the parent node to it's child. In my opinion, this operation should be performed implicitly by the existing ``add_child()`` method.

**Comment by zbyte64** [comment] 2017-07-05 18:13
I am not sure I understand what exactly this means and I can't find mention of it in the docs. Does this mean one should refrain from calling 'Node.add_root()` more then once (ie add more then one root node)?

**Comment by jrief** [comment] 2017-07-05 21:04
No, calling ``Node.add_root()`` more than once is perfectly legitimate. However, if you intend to have more than one root, usually you need an attribute to distinguish the trees. Here django-treebeard does not offer any solution which automatically copies that attribute when adding children.

**Comment by schwobaseggl** [comment] 2017-11-08 16:01
Wouldn't such an extra field constitute some denormalization since `node.path[:node.steplen]` already constitutes such a property that is equal for all and only the nodes descending from a single root (and which is relatively easily db-queryable)?

**Comment by taqi457** [comment] 2018-08-09 14:28
Same thing for Adjacency List, why can't we have multiple parents for one node ?
I know that that the resulting data structure would not be a tree but a graph, but it would allow a more generalized approach no?

I am currently thinking of overriding the functions myself...

**Comment by ca-simone-chiorazzo** [comment] 2020-08-27 09:49
Any news on this? We have the same issue implementing the materialized tree path, we would create different trees based on an extra field but seems not possible now. Do you know if there is some example of segregation of the trees overriding the library methods?

**Comment by danish-wani** [comment] 2020-09-15 16:23
@jrief Any update on this? Can we add multiple trees now?

**Comment by jrief** [comment] 2020-09-15 21:26
@danish-wani I'm sorry, but this feature hasn't been implemented yet.

**Comment by danish-wani** [comment] 2020-09-16 04:47
@jrief Thank you. As per my requirement, I may have to switch to **https://github.com/django-mptt/django-mptt**  now instead. Would be much appreciated if the multiple trees feature is implemented in **django-treebeard** in near future.

**Comment by jrief** [comment] 2020-09-16 13:44
Please consider, that django-mptt has a different API and you may experience other problems, such as tree corruption, if transactions can't be closed properly.
Which kind of tree model did you choose in treebeard?

**Comment by danish-wani** [comment] 2020-09-17 17:38
@jrief I used Materialized Path Trees. Yes I did face some problems while changing parent of nodes in django-mptt. But their manager method `rebuild` seems to fix corruption of relations. I'm still in my initial phase of implementation, will try to find work around in treebeard itself only, I hope I come up with something.
Thank you so much for your valuable time and response, I really appreciate it.

**Comment by tabo** [comment] 2021-01-17 10:45
Isn't this exactly what [`get_root()`](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.get_root) does?

**Comment by danish-wani** [comment] 2021-01-17 12:09
I finally used https://pypi.org/project/django-treenode/ which was a perfect fit for my requirements.

By : https://github.com/fabiocaccamo

**Comment by danish-wani** [comment] 2021-01-17 12:11
> Isn't this exactly what [`get_root()`](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.get_root) does?

No, get_root() gives the current node's root. That's different then having multiple trees

**Comment by tabo** [comment] 2021-01-17 12:25
Perhaps I'm misunderstanding. When calling .[`add_root()`](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.add_root), treebeard is adding "a separate tree" that starts in that root. All the child nodes will belong to that root. Calling another `add_root()` will start a whole different tree under that model, with its own set of child nodes. You can move nodes between trees, but each node has a single "root" node that identifies its tree. You can get this single root node with [`get_root()`](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.get_root)

**Comment by danish-wani** [comment] 2021-01-17 12:29
> Perhaps I'm misunderstanding. When calling .[`add_root()`](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.add_root), treebeard is adding "a separate tree" that starts in that root. All the child nodes will belong to that root. Calling another `add_root()` will start a whole different tree under that model, with its own set of child nodes. You can move nodes between trees, but each node has a single "root" node that identifies its tree. You can get this single root node with [`get_root()`](https://django-treebeard.readthedocs.io/en/latest/api.html#treebeard.models.Node.get_root)


That's where the issue exists, moving the nodes between trees. I don't have right now the exact description and screenshots but yeah that's where the problem is. I can recall of one thing, when there are more than one root node with no descendants only of them is declared as leaf mode by the tree beard Library.

**Comment by tabo** [comment] 2021-01-18 06:51
@danish-wani  I [added a test](b8e07b3fadcefa2fcd02083fd1ebb8b5920c4540) dsa that excercises your concerns with multiple root node additions not creating leaf nodes, just to confirm treebeard is working as expected.

Regarding problems with moving nodes to other trees, we have plenty of testing for moves and they all pass. Could you please contribute a test case that demonstrate this is a problem?

The problems described seem to me like an [issue with manager overriding](https://django-treebeard.readthedocs.io/en/latest/mp_tree.html#treebeard.mp_tree.MP_Node):

> If you need to define your own Manager class, you’ll need to subclass MP_NodeManager.
> 
> Also, if in your manager you need to change the default queryset handler, you’ll need to subclass MP_NodeQuerySet.

I'm closing this ticket because the problem originally described, having multiple tree roots, is working as expected.

**Closed by tabo** 2021-01-18 06:51 UTC

**Comment by opentyler** [comment] 2021-01-18 16:33
Sorry to add to a closed topic, but aren't the number of multiple tree roots in django-treebeard still limited? E.g. 0001, 0002... ZZZZ. That leaves room for a lot of tree roots, but it's still a small finite number and thus unsuitable for uses where millions of unique tree roots are required. Or am I missing something? I've found myself monkeypatching treebeard to include a tree_root_pk variable that allows differentiating an open-ended number of tree roots and it works suprisingly well with only small changes. I'm under the impression this is still necessary because of the finite # of tree roots treebeard supports by default.

**Comment by robslotboom** [comment] 2021-11-19 12:17
@opentyler, Where did you add the tree_root_pk variable?
As a field in a custom model?

**Comment by devanghingu** [comment] 2022-12-22 11:00
@tabo @jrief is there any update on this? i want to multiple parent(arbitrary graph) with more than 50 level in sql.
