### ISSUE TITLE
What should I do if I don't like the default fields name.

### ISSUE THREAD

**Issue by oraant** [django-treebeard/django-treebeard#173] opened 2020-08-14 06:50 UTC
In AL_Node, we must use 'parent' field to make it work, but we already using 'father' or 'fid' for a long time.

To change everything from 'fid' to 'parent' will cost a lot, so is there anyway to let AL_Node know that 'fid' is the 'parent' field that he need.

**Comment by jrief** [comment] 2020-08-14 11:44
You can create a Python `@property` which points onto the `parent` field.

**Comment by oraant** [comment] 2020-08-15 07:14
@jrief Like this?

```
    pid = models.ForeignKey('self', models.CASCADE, db_column='pid', blank=True, null=True, related_name='children_set')

    @property
    def parent(self):
        return self.pid

    @parent.setter
    def parent(self, value):
        self.pid = value
```

Django said `Cannot resolve keyword 'parent' into field`

----------

Or this?

```
    parent = models.ForeignKey('self', models.CASCADE, db_column='pid', blank=True, null=True, related_name='children_set')

    @property
    def pid(self):
        return self.parent

    @pid.setter
    def pid(self, value):
        self.parent = value
```

That works in Admin, but django-restful-framework said `Object of type NavCategory is not JSON serializable`

-----------

Anyway, thanks for the response. Hope you have a nice day.

**Comment by tabo** [comment] 2021-01-18 11:52
Hope you could solve your problem. I'm closing this ticket as a duplicate of #45

**Closed by tabo** 2021-01-18 11:52 UTC
Labels: feature request

**Comment by oraant** [comment] 2021-02-22 14:19
> Hope you could solve your problem. I'm closing this ticket as a duplicate of #45

Sorry I didn't, bad story.
