### ISSUE TITLE
Admin page popups works incorrectly 

### ISSUE THREAD

**Issue by sobolevn** [django-treebeard/django-treebeard#126] opened 2018-11-06 12:38 UTC
Problem: when using `raw_id_fields` and `TreeAdmin` admin model the item-selection popup does not select an item.

It just falls into the editing instead:

![2018-11-06 15 36 44](https://user-images.githubusercontent.com/4660275/48064747-c8ee1880-e1d9-11e8-9a93-2dd170c4dd1e.png)

## Models

My user model:

```python
from django.db import models


class ApplicationUser(models.Model):
    """
    This model represents an application user.

    Attributes:
        ...

    """

    # Identity:
    email = CIEmailField(unique=True)

    # Logic:
    unit = models.ForeignKey(
        'OrganizationStructure',
        related_name='users',
        default=None,
        null=True,
        blank=True,
    )
```

My `django-treebeard` model:

```python
from treebeard.mp_tree import MP_Node


class OrganizationStructure(MP_Node):
    """
    This model represents a unit in complex nested organization structure.

    Attributes:
        uid (CharField): unique unit id provided by the client.
            It may be blank, since some root nodes do not have this number.
        name (CharField): unit's name.

    """

    # Logic:
    uid = models.CharField(max_length=140, blank=True)
    name = models.CharField(max_length=140)

    # Utils:
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Model is converted to string primarily in admin site."""
        return self.name
```

## Admin 

My user model:

```python
from django.contrib import admin

@admin.register(ApplicationUser)
class ApplicationUserAdmin(admin.ModelAdmin):
    """Admin resource to manage `ApplicationUser`."""

    list_display = (
        'email',
    )
    raw_id_fields = ('unit',)
```

My `django-treebeard` model:

```python
from treebeard.admin import TreeAdmin

@admin.register(OrganizationStructure)
class OrganizationStructureAdmin(TreeAdmin):
    """Admin resource to manage `OrganizationStructure`."""

    # FIXME(@sobolevn): this form does not allow to move sub nodes,
    # there is a bug in `django-treebeard`.
    # https://github.com/django-treebeard/django-treebeard/issues/92
    form = movenodeform_factory(OrganizationStructure)
```

## Links

Each item in this popup has a unique link, so you can click it to select what item you want to choose. I see that there's a difference between how these links look like.

Correct link from another model, works fine: http://127.0.0.1:8000/admin/bot_app/office/2/change/?_changelist_filters=_to_field%3Did%26_popup%3D1

How it looks like: 
![2018-11-06 15 27 15](https://user-images.githubusercontent.com/4660275/48064317-82e48500-e1d8-11e8-8fc5-3b975eb02339.png)

Generated by `django-treebeard`: http://127.0.0.1:8000/admin/bot_app/organizationstructure/4/change/

How it looks like:
![2018-11-06 15 26 59](https://user-images.githubusercontent.com/4660275/48064327-8a0b9300-e1d8-11e8-8c0c-9170b7f08b0a.png)

When I click on any node, I will see an editing window. Nothing will be selected on the original page.

## Versions

- `python3.6`
- `django@1.11.16`
- `django@4.3`

**Comment by solarissmoke** [comment] 2023-01-02 04:24
I've tested this on the latest version of Treebeard (4.6.0) and Django 4.2, and can't reproduce the issue - selecting an item in the popup correctly closes the popup and sets the value in the parent form. I'm going to close this on that basis - if it's still an issue, please feel free to reopen with any additional details that can be used to reproduce the problem.

**Closed by solarissmoke** 2023-01-02 04:24 UTC
Labels: bug, admin
