### ISSUE TITLE
No way to avoid errors with MP trees on MySQL

### ISSUE THREAD

**Issue by morganwahl** [django-treebeard/django-treebeard#56] opened 2017-03-15 16:14 UTC
I actually don't know if this is MySQL/MariaDB specific or not, but here's the problem I'm having:

MySQL defaults to "repeatable read" isolation level. This basically means a given transaction always gets the same data when it read a table, even if other transactions have since updated that table. This can make it impossible for treebeard to calculate the right values for an MP_Node's fields.

I have a test for my own code that's failing because of this; I haven't boiled it down to a treebeard-only test yet, and I don't totally understand the test layout in treebeard's code, but I think this would demonstrate the problem:

Example:

```py
class Node(MP_Node):
    node_order_by = ('key',)
    key = models.CharField(unique=True, max_length=32)
```

```py
with transaction.atomic():
    # time 1
    MP_Node.add_root(key='b')
    # time 2
```

```py
with transaction.atomic():
    # time 0
    some_nodes = MP_Node.objects.all()
    # some_nodes is empty
    # time 3
    some_nodes = MP_Node.objects.all()
    # some_nodes is still empty
    MP_Node.add_root(key='a')
    # time 4
```

The second transaction tries to use the same path as the first, and fails. There doesn't seem to be any way to address this even with locking, since the database will always give the table as it existed at the start of the transaction.

**Comment by jrief** [comment] 2017-03-15 18:18
Isn't this a duplicate of #53?

**Comment by morganwahl** [comment] 2020-10-15 21:02
#53 Might be solvable for some databases by using `SELECT FOR UPDATE` on the table. As far as I can tell, that won't fix things on MySQL/MariaDB with their default isolation level. Changing the isolation level to "serializable" I think would make this work, but that can cause a serious drop in performance. (Which is presumably why it's not the default.)

It's possible this is just a more specific variant of #53. Either way, this seems like it maybe actually be a fundamental problem with MP in practice, or maybe is just a problem with the `node_order_by` feature.

**Comment by tabo** [comment] 2021-01-18 08:44
@morganwahl this is the way the SQL standard expects transactions to work. When using transactions with repeatable reads, they will work exactly like that. This isn't MySQL specific. Any other DBMS using repeatable reads behaves this way.

How long living are your transactions? Sounds like you need to make them shorter

I am closing this issue because, again, this is literally what SQL is guaranteeing.

**Closed by tabo** 2021-01-18 08:44 UTC
Labels: Materialized Path, MySQL, invalid
